# Version 1.0.1 (FIX INPUT OF POLYLINT AS IT FAILS WITH INDEX.HTML)
language: node_js
sudo: false
node_js:
  - stable
addons:
  firefox: '42.0'

before_script:
  - npm install web-component-tester
  - npm install bower
  - bower install
  - npm install polylint
  - polylint -i paper-contact.html
  - export PATH=$PWD/node_modules/.bin:$PATH

script:
  - xvfb-run wct
  - ./gpages_build.sh Collaborne info@collaborne.com
